"""add referrers and time spent on page

Revision ID: 6266055f5166
Revises: 
Create Date: 2025-10-26 07:30:01.483148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6266055f5166'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pageviews', sa.Column('referrer', sa.String(), nullable=False), server_default="")
    op.add_column('pageviews', sa.Column('time_spent_on_page', sa.Integer(), nullable=False, server_default=0))
    with op.batch_alter_table("pageviews") as batch_op:
        batch_op.alter_column("referrer", server_default=None)
        batch_op.alter_column("time_spent_on_page", server_default=None)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pageviews', 'time_spent_on_page')
    op.drop_column('pageviews', 'referrer')
    # ### end Alembic commands ###
