"""add view id to pageviews

Revision ID: cfcc4f37eab6
Revises: 6266055f5166
Create Date: 2025-10-26 11:09:17.571732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcc4f37eab6'
down_revision: Union[str, Sequence[str], None] = '6266055f5166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('pageviews', sa.Column('view_id', sa.String(), nullable=True, default="972a 854b bffd 5107 6739 548a 9002 c605"))
    with op.batch_alter_table("pageviews") as batch_op:
        batch_op.alter_column(
            "view_id",
            server_default=None,
            existing_type=sa.String(),
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pageviews', 'view_id')
    # ### end Alembic commands ###
